version: '3'

services:

  dev:
    container_name: music-genres-front-dev
    image: paulintrognon/music-genres-front-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - ${DEV_PORT:-3000}:3000
      - 35729:35729
    volumes:
      - .:/usr/src/app

  prod:
    container_name: music-genres-front
    image: paulintrognon/music-genres-front
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 127.0.0.1:${PORT:-80}:3000
